/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejer8.interfazGUI;

import ejer8.concesionario.Coche;
import ejer8.utilidades.GestorCoches;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristina
 */
public class VentanaListado extends javax.swing.JFrame implements ListSelectionListener {

    DefaultTableModel tablaModelo;

    /**
     * Creates new form VentanaListado
     */
    public VentanaListado() {
        initComponents();
        this.setVisible(true);
        tablaModelo = (DefaultTableModel) tabla.getModel();
        creaTabla();
    }

    public void creaTabla() {
        //le pido los datos de los coches a GestorCoches

        String[] nombreColumnas = {"MATRICULA", "MODELO", "KM"};
        String[][] datos = GestorCoches.getCoches();
        tablaModelo.setDataVector(datos, nombreColumnas);        

        //añadimos el accion listener
        ListSelectionModel modeloSeleccion = tabla.getSelectionModel();
        modeloSeleccion.addListSelectionListener(this);
    }
    
    
    
   public void refrescaTabla() {
       String[] nombreColumnas = {"MATRICULA", "MODELO", "KM"};
//               String[][] datos = GestorCoches.getCoches();
//        tablaModelo.setDataVector(datos, nombreColumnas);    

//pedir la lista de coches 
//vaciar la table
        for(Coche c: GestorCoches.getListaCoches()) {
            tablaModelo.addRow(c.toArray());
        }

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        etDibujo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btBorrar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        vtCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AUTOMÓVILES ACME");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        etTitulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        etTitulo.setForeground(new java.awt.Color(204, 0, 0));
        etTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etTitulo.setText("LISTADO");

        etDibujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miAudi.png"))); // NOI18N

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btBorrar.setText("BORRAR");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        btModificar.setText("MODIFICAR");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar Selección");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        vtCerrar.setText("CERRAR");
        vtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 16, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btBorrar)
                        .addGap(47, 47, 47)
                        .addComponent(btModificar)
                        .addGap(28, 28, 28)
                        .addComponent(btLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vtCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etDibujo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBorrar)
                    .addComponent(btModificar)
                    .addComponent(btLimpiar)
                    .addComponent(vtCerrar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        VentanaPrincipal v = new VentanaPrincipal();
    }//GEN-LAST:event_formWindowClosed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here
        int numFilasSelected = tabla.getSelectedRowCount();
        int op = JOptionPane.showConfirmDialog(this, "Se van a eliminar " + String.valueOf(numFilasSelected) + " filas???", "ACME", JOptionPane.YES_NO_OPTION);

        if (op == 0) {
            int filasSelected[] = tabla.getSelectedRows();
            //tenemos que eliminar las filas de abajo para arriba
            for (int i = filasSelected.length - 1; i >= 0; i--) {
                String matricula = (String) tablaModelo.getValueAt(filasSelected[i], 0);
                GestorCoches.bajaCoche(GestorCoches.buscaCoche(matricula));
//                tablaModelo.removeRow(filasSelected[i]);
            }
            refrescaTabla();
        }
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        if (tabla.getSelectedRowCount() != 1 || tabla.getSelectedColumnCount() != 1) {
            JOptionPane.showMessageDialog(this, "Solo puedes modificar un valor", "ACME", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int fila = tabla.getSelectedRow();
            int col = tabla.getSelectedColumn();
            String nuevoDato = JOptionPane.showInputDialog(this, "Introduce el nuevo valor: ");
            Coche c = GestorCoches.buscaCoche((String) tablaModelo.getValueAt(fila, 0));
            try {
                switch (col) {
                    case 0:
                        c.setMatricula(nuevoDato);
                        break;
                    case 1:
                        c.setModelo(nuevoDato);
                        break;
                    case 3:
                        c.setKm(nuevoDato);
                        break;
                }
                tablaModelo.setValueAt(nuevoDato, fila, col);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ACME", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btModificarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
//        System.out.println(tablaModelo.getRowCount());
        if (tabla.getSelectedRowCount()>0) {
        tabla.clearSelection();
        } else {
            JOptionPane.showMessageDialog(this, "No hay filas seleccionadas", "ACME", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void vtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_vtCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btModificar;
    private javax.swing.JLabel etDibujo;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton vtCerrar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent lse) {

    }

//    @Override
//    public void valueChanged(ListSelectionEvent lse) {
//        System.out.println("valueChanged");
//    }
}
